name: Publish
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 */6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Requirements
        run: pip install -r requirements.txt

      - name: Render
        run: |
          mkdir -p public
          jupyter nbconvert \
            --execute \
            --no-prompt \
            --output public/index.html \
            --TemplateExporter.exclude_input=True \
            --to html \
            ncov19-id-analysis.ipynb

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
